targets:
  $default:
    builders:
      json_serializable:
        enabled: true
        generate_for:
          include:
            - lib/src/data/dto/*.dart
        options:
          explicit_to_json: true
          create_to_json: false
